= Solution for chart per service approach with Helm Charts in Openshift

:home: https://github.com/IBM

* <<preparation, Preparation>>
* <<helm-chart-setup-for-the-microservice, Helm chart setup for the microservice >>
** <<replicate-the-installation-in-qa-project, Replicate the installation in qa project>>
* <<validation-and-more_, Validation and more>>
* <<compatibility,Compatibility>>
* <<license,License>>

Use a Helm chart per microservice approach if you seek to achieve flexible, simple versioning and low complexity charts to package your application.
Be careful, this technique might bring:

• huge amount of duplication
• difficulty to keep consistent many templates
• hardship to introduce global changes

**Goal of this section: deploy the landmark microservice using Helm charts.
**

All the below commands will be executed in a terminal window.

=== Preparation

Assuming that you already cloned the landmark project, execute the following:

[source, bash, subs="normal,attributes"]
----
$ git checkout solution/chart-per-service-lab
$ git pull
----

To login to the OpenShift cluster from the Terminal run:

[source, bash, subs="normal,attributes"]
----
$ oc login -u kubeadmin -p YOUR_SECRET_PASSWORD https://api.crc.testing:6443
----
Check if you already have the _dev_ project:
----
$ oc get project
$ oc new-project dev
----

The landmark microservice will persist its data into a database, in this case a PostgreSQL database instance.

In order to install the database, the PostgreSQL Helm Charts will be used. Check if the Helm repo https://charts.bitnami.com/bitnami[https://charts.bitnami.com/bitnami] is added to your existing list:
[source, bash, subs="normal,attributes"]
----
$ helm repo list
----
If the repo is not there, please run the following set of commands:
[source, bash, subs="normal,attributes"]
----
$ helm repo add bitnami https://charts.bitnami.com/bitnami
----

Setup the database instance with Helm, using the following command:

[source, bash, subs="normal,attributes"]
----
$ helm install landmark-db \
--set postgresqlUsername=landmark-default,postgresqlPassword=postgres,postgresqlDatabase=landmark,persistence.enabled=false \
stable/postgresql
$ helm status landmark-db
----
Validate the installation via:

[source, bash, subs="normal,attributes"]
----
$ helm list
$ helm get all landmark-db
----

=== Helm chart setup for the microservice

Install your charts in dev project
[source, bash, subs="normal,attributes"]
----
$ helm install simple ./chart/landmark
$ helm status simple
$ kubectl get ns
$ kubectl get svc
$ kubectl port-forward --namespace dev svc/simple-landmark 8080
----


Go in a browser window and copy-paste http://localhost:8080/api/museum/museum

*Congratulations*, you found a landmark!

==== Replicate the installation in _qa_ project
====== Step1

According to Openshift documentation _a project is a Kubernetes namespace with additional annotations, and is the central vehicle by which access to resources for regular users is managed._
This means that a project offers you the ability to deploy Helm charts without specifying the namespace.

Create _qa_ project and install a PostgreSQL instance:

[source, bash, subs="normal,attributes"]
----
$ oc new-project qa
$ helm install landmark-db \
--set postgresqlUsername=landmark-default,postgresqlPassword=postgres,postgresqlDatabase=landmark,persistence.enabled=false \
stable/postgresql
$ helm status landmark-db
----

====== Step2
Duplicate the _values.yaml_ and rename it to _values.qa.yaml_.
Change the NodePort value in _values.qa.yaml_ to 31126.
Install the charts:
[source, bash, subs="normal,attributes"]
----
$ helm install simple ./chart/landmark --values ./chart/landmark/values.qa.yaml
$ helm status simple
$ kubectl get ns
$ kubectl get svc
$ kubectl port-forward --namespace qa svc/simple-landmark 8080
----
Go in a browser window and copy-paste http://localhost:8080/api/museum/museum

*Congratulations*, you found a landmark and replicated deployment process accros environments!

In order to switch back to project dev, use the below command:
[source, bash, subs="normal,attributes"]
----
$ oc project dev
----

=== Validation and more

Looking to validate your charts? 
Checkout the validation branch: {home}/landmark/tree/validation/chart-per-service-lab


|===
|{home}/helm-openshift-workshop[Navigate to global instructions] | {home}/landmark[Navigate to previous section] | {home}/landmark/tree/feature/leader-chart-lab[Navigate to next section]
|===

'''
=== Compatibility

The Java code in the repositories is compatible with Java11.

'''
=== License

This code is dedicated to the public domain to the maximum extent permitted by applicable law, pursuant to http://creativecommons.org/publicdomain/zero/1.0/[CC0].
