= Solution for Leader chart approach with Helm Charts in Openshift

* <<preparation, Preparation>>
** <<create-the-docker-image-for-landmark-microservice, Create the Docker image for Landmark Microservice>>
* <<leader-helm-chart-setup,  Leader Helm chart setup>>
* <<validation-and-more, Validation and more>>
* <<compatibility,Compatibility>>
* <<license,License>>

All the below commands will be executed in a terminal window.

=== Preparation

Assuming that you already clone the landmark project, execute the following:

[source, bash, subs="normal,attributes"]
----
$ git checkout solution/leader-chart-lab
$ git pull
----

To login to the OpenShift cluster from the Terminal run:

[source, bash, subs="normal,attributes"]
----
$ oc login -u kubeadmin -p YOUR_SECRET_PASSWORD https://api.crc.testing:6443
----
Check if you already have the _dev_ project:
----
$ oc get project
$ oc new-project dev
$ oc project dev
----

The landmark microservice will persist its data into a database, in this case a PostgreSQL database instance.

Check if the Helm repo https://charts.bitnami.com/bitnami[https://charts.bitnami.com/bitnami] is added to your existing list:
[source, bash, subs="normal,attributes"]
----
$ helm repo list
----
If the repo is not there, please run the following set of commands:
[source, bash, subs="normal,attributes"]
----
$ helm repo add bitnami https://charts.bitnami.com/bitnami
----

==== Create the Docker image for Landmark Microservice
Clone the repository https://github.com/ammbra/landmark[https://github.com/ammbra/landmark]:

[source, bash, subs="normal,attributes"]
----
$ git clone https://github.com/ammbra/landmark
$ git checkout solution/leader-chart-lab
$ git pull
----

Try to build the project locally using <<Run-Landmark-Microservice.adoc#, Run-Landmark-Microservice.adoc>>.

Make sure that you are under root folder of the clone repository (_landmark_) and run:
[source, bash, subs="normal,attributes"]
----
$ mvn package
----
Then, build the image with:
[source, bash, subs="normal,attributes"]
----
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
$ docker build -f src/main/docker/Dockerfile.jvm -t quarkus/landmark:1.0 .
$ docker tag quarkus/landmark:1.0 localhost:5000/quarkus/landmark:1.0
$ docker push localhost:5000/quarkus/landmark:1.0
----

=== Leader Helm chart setup
Observe the json schema used to validate the charts.
Install your charts in your current project:

[source, bash, subs="normal,attributes"]
----
$ helm install leader ./leader
$ helm status leader
$ kubectl get ns
$ kubectl get svc
$ kubectl port-forward --namespace dev svc/leader-landmark 8080
----

Go in a browser window and copy-paste http://localhost:8080/api/museum/ams

*Congratulations*, you found a landmark!

=== Validation and more

Looking to validate your charts? Checkout the validation branch: https://github.com/ammbra/landmark/tree/validation/leader-chart-lab

|===
|https://github.com/ammbra/helm-openshift-workshop[Navigate to global instructions] | https://github.com/ammbra/landmark/tree/feature/chart-per-service-lab[Navigate to previous section] | https://github.com/ammbra/visitor[Navigate to next section]
|===

'''
=== Compatibility

The Java code in the repositories is compatible with Java11.

'''
=== License

This code is dedicated to the public domain to the maximum extent permitted by applicable law, pursuant to http://creativecommons.org/publicdomain/zero/1.0/[CC0].
